"""
Auto-generated tests for Python.api.schemas module.

Generated by Test Framework v2.1.0
DO NOT EDIT MANUALLY - regenerate with: pytest --generate-tests
"""

from datetime import datetime, timezone

import jax.numpy as jnp
import pytest

from Python.api.schemas import (
    HealthCheckResponseSchema,
    KernelOutputSchema,
    OperatingMode,
    PredictionResultSchema,
    ProcessStateSchema,
    TelemetryDataSchema,
)


@pytest.mark.api
class TestPythonApiSchemas:
    """Auto-generated tests for Python.api.schemas module."""

    def test_operatingmode_executes(self):
        """Execute: OperatingMode - class instantiation test."""
        instance = OperatingMode.INFERENCE
        assert instance is not None

    def test_processstateschema_executes(self):
        """Execute: ProcessStateSchema - class instantiation test."""
        instance = ProcessStateSchema(
            magnitude=jnp.array([1.0]),
            timestamp_utc=datetime.now(timezone.utc),
        )
        assert instance is not None

    def test_kerneloutputschema_executes(self):
        """Execute: KernelOutputSchema - class instantiation test."""
        instance = KernelOutputSchema(
            probability_density=jnp.array([1.0]),
            kernel_id=0,
            computation_time_us=1.0,
        )
        assert instance is not None

    def test_telemetrydataschema_executes(self):
        """Execute: TelemetryDataSchema - class instantiation test."""
        instance = TelemetryDataSchema(
            step_index=0,
            jax_device="cpu",
            timestamp_utc=datetime.now(timezone.utc),
        )
        assert instance is not None

    def test_predictionresultschema_executes(self):
        """Execute: PredictionResultSchema - class instantiation test."""
        instance = PredictionResultSchema(
            reference_prediction=jnp.array(0.5),
            confidence_lower=jnp.array(0.0),
            confidence_upper=jnp.array(1.0),
            operating_mode=OperatingMode.INFERENCE,
        )
        assert instance is not None

    def test_healthcheckresponseschema_executes(self):
        """Execute: HealthCheckResponseSchema - class instantiation test."""
        instance = HealthCheckResponseSchema(
            status="healthy",
            version="v0",
            jax_config={},
            uptime_seconds=0.0,
        )
        assert instance is not None
